/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.MProveedores;

/**
 *
 * @author alijm
 */
public class VProveedores extends javax.swing.JFrame {

     private final MProveedores prov = new MProveedores();
    String correo1i,correo2i,correo3i;
    String tl1,tl2,tl3;
    String li1,li2,li3;
    //Atributos de la clase2222
    private int tipo;
    private String username;
    DefaultListModel<String> model = new DefaultListModel<>();

    public VProveedores() {       
        initComponents();
         this.tableProveedores.setModel(prov.mostrarDatosProveedor()); 
    }
    
    //sobrecarga del constructor principal
    public VProveedores(int tipo, String username) {
        initComponents();
        this.tipo = tipo;
        this.username = username;
        prov.obtenerLinea(LineaSuminist1);
        prov.obtenerLinea(LineaSuminist2);
        prov.obtenerLinea(LineaSuminist3);
      this.tableProveedores.setModel(prov.mostrarDatosProveedor()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        FieldRIF = new javax.swing.JTextField();
        FieldRS = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        FieldDirec = new javax.swing.JTextField();
        FieldMail1 = new javax.swing.JTextField();
        MasMail = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        FieldMail2 = new javax.swing.JTextField();
        FieldMail3 = new javax.swing.JTextField();
        FieldTlf1 = new javax.swing.JTextField();
        MasTlf = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        FieldTlf2 = new javax.swing.JTextField();
        FieldTlf3 = new javax.swing.JTextField();
        LineaSuminist1 = new javax.swing.JComboBox<String>();
        jLabel16 = new javax.swing.JLabel();
        LineaSuminist2 = new javax.swing.JComboBox<String>();
        LineaSuminist3 = new javax.swing.JComboBox<String>();
        jPanel4 = new javax.swing.JPanel();
        Nuevo1 = new javax.swing.JButton();
        Actualizar1 = new javax.swing.JButton();
        Guardar1 = new javax.swing.JButton();
        LimpiarTodo1 = new javax.swing.JButton();
        Eliminar1 = new javax.swing.JButton();
        VerInfo1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProveedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 720));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Proveedores");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(580, 350));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("RIF:");

        FieldRIF.setEnabled(false);
        FieldRIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldRIFActionPerformed(evt);
            }
        });

        FieldRS.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("RAZÓN SOCIAL:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("DIRECCION:");

        FieldDirec.setEnabled(false);

        FieldMail1.setEnabled(false);

        MasMail.setText("+");
        MasMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasMailActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("E-MAIL:");

        FieldMail2.setEnabled(false);

        FieldMail3.setEnabled(false);

        FieldTlf1.setEnabled(false);

        MasTlf.setText("+");
        MasTlf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasTlfActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("TELEFONO:");

        FieldTlf2.setEnabled(false);
        FieldTlf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldTlf2ActionPerformed(evt);
            }
        });

        FieldTlf3.setEnabled(false);

        LineaSuminist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineaSuminist1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("LINEA DE SUMINISTRO:");

        LineaSuminist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineaSuminist2ActionPerformed(evt);
            }
        });

        LineaSuminist3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineaSuminist3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldRIF, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldRS, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(72, 72, 72)
                                .addComponent(MasMail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FieldMail1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(72, 72, 72)
                                .addComponent(MasTlf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FieldTlf1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LineaSuminist3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LineaSuminist2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LineaSuminist1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(FieldMail2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(FieldMail3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(FieldTlf2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(FieldTlf3, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(59, 59, 59))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldRIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldDirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldMail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MasMail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FieldMail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FieldMail3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldTlf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MasTlf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FieldTlf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FieldTlf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LineaSuminist1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(LineaSuminist2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LineaSuminist3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        Nuevo1.setText("NUEVO");
        Nuevo1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nuevo1ActionPerformed(evt);
            }
        });

        Actualizar1.setText("ACTUALIZAR");
        Actualizar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Actualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Actualizar1ActionPerformed(evt);
            }
        });

        Guardar1.setText("GUARDAR");
        Guardar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar1ActionPerformed(evt);
            }
        });

        LimpiarTodo1.setText("LIMPIAR TODO");
        LimpiarTodo1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LimpiarTodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarTodo1ActionPerformed(evt);
            }
        });

        Eliminar1.setText("ELIMINAR");
        Eliminar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar1ActionPerformed(evt);
            }
        });

        VerInfo1.setText("VER + INFO");
        VerInfo1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        VerInfo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerInfo1MouseClicked(evt);
            }
        });
        VerInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerInfo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VerInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Eliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LimpiarTodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Actualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(Guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Actualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VerInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LimpiarTodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/designs/Volver.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tableProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProveedoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableProveedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
       new MainMenu(this.tipo,this.username).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Nuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nuevo1ActionPerformed

        this.FieldRIF.setEnabled(true);
        this.FieldRS.setEnabled(true);
        this.FieldDirec.setEnabled(true);
        this.FieldMail1.setEnabled(true);
        this.FieldTlf1.setEnabled(true);
        this.LineaSuminist1.setEnabled(true);
    }//GEN-LAST:event_Nuevo1ActionPerformed

    private void Actualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Actualizar1ActionPerformed
        if (!(this.FieldRIF.getText().equals("")) && !(this.FieldRS.getText().equals("")) && !(this.FieldDirec.getText().equals(""))) {
            int decision = JOptionPane.showConfirmDialog(null, "**Desea actualizar los datos modificados del proveedor?**");
            if (decision == 0) { //Caso que se acepte.
                //razon social y direccion
                prov.actualizarDatosProveedores(Integer.parseInt(this.FieldRIF.getText()), this.FieldRS.getText(), this.FieldDirec.getText());
                //correos
                prov.actualizarDatosCorreos(Integer.parseInt(this.FieldRIF.getText()),this.FieldMail1.getText(),this.FieldMail2.getText(),this.FieldMail3.getText(), correo1i, correo2i,correo3i);
                //telefonos
                prov.actualizarDatosTelefonos(Integer.parseInt(this.FieldRIF.getText()), this.FieldTlf1.getText(),this.FieldTlf2.getText(),this.FieldTlf3.getText(),tl1,tl2,tl3);
                //lineas de suministros
                prov.actualizarDatosLineas(Integer.parseInt(this.FieldRIF.getText()), this.LineaSuminist1.getSelectedItem().toString(), this.LineaSuminist2.getSelectedItem().toString(), this.LineaSuminist3.getSelectedItem().toString(), li1, li2, li3);
                //Se vuelve a mostrar la tabla actualizada:
                this.tableProveedores.setModel(prov.mostrarDatosProveedor());
            }
        }
        else
        JOptionPane.showMessageDialog(null, "Por favor rellene los campos faltantes", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_Actualizar1ActionPerformed

    private void Guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar1ActionPerformed
        if (!(this.FieldRIF.getText().equals("")) && !(this.FieldRS.getText().equals("")) && !(this.FieldDirec.getText().equals("")) && !(this.LineaSuminist1.getSelectedItem().toString().equals("")) && !(this.LineaSuminist2.getSelectedItem().toString().equals("")) && !(this.LineaSuminist3.getSelectedItem().toString().equals(""))) {
            //Se toman los valores de los fields para convertirlos en datos para el campo:
            int RIF = Integer.parseInt(this.FieldRIF.getText());
            String RS = this.FieldRS.getText();
            String DIREC = this.FieldDirec.getText();
            String MAIL1 = this.FieldMail1.getText();
            String MAIL2 = this.FieldMail2.getText();
            String MAIL3 = this.FieldMail3.getText();
            String TLF1 = this.FieldTlf1.getText();
            String TLF2 = this.FieldTlf2.getText();
            String TLF3 = this.FieldTlf3.getText();
            String CODL1 = this.LineaSuminist1.getSelectedItem().toString();
            String CODL2 = this.LineaSuminist2.getSelectedItem().toString();
            String CODL3 = this.LineaSuminist3.getSelectedItem().toString();
            prov.insertarDatosProveedores(RIF, RS, DIREC, 'A');

            if(!(this.FieldMail1.getText().equals(""))){
                prov.insertarDatosCORREOS(RIF, MAIL1);
            }
            if(!(this.FieldMail2.getText().equals(""))){
                prov.insertarDatosCORREOS(RIF, MAIL2);
            }
            if(!(this.FieldMail3.getText().equals(""))){
                prov.insertarDatosCORREOS(RIF, MAIL3);
            }
            if(!(this.FieldTlf1.getText().equals(""))){
                prov.insertarDatosTelefonos(RIF, TLF1);
            }
            if(!(this.FieldTlf2.getText().equals(""))){
                prov.insertarDatosTelefonos(RIF, TLF2);
            }
            if(!(this.FieldTlf3.getText().equals(""))){
                prov.insertarDatosTelefonos(RIF, TLF3);
            }
            if(!(this.LineaSuminist1.getSelectedItem().toString().equals(""))){
                prov.insertarDatossuministran(RIF,CODL1);
            }

            if(!(this.LineaSuminist2.getSelectedItem().toString().equals(""))){
                prov.insertarDatossuministran(RIF,CODL2);
            }
            if(!(this.LineaSuminist3.getSelectedItem().toString().equals(""))){
                prov.insertarDatossuministran(RIF,CODL3);
            }
            //Se insertan la fila nueva en la bd: (Funcion no hecha aun)
            //lineas.insertarDatosLineas(codlineas, descripcionl);

            //Se colocan los cambios deshabilitados de nuevo
            this.FieldRIF.setEnabled(false);
            this.FieldRS.setEnabled(false);
            this.FieldDirec.setEnabled(false);
            this.FieldMail1.setEnabled(false);
            this.FieldMail2.setEnabled(false);
            this.FieldMail3.setEnabled(false);
            this.FieldTlf1.setEnabled(false);
            this.FieldTlf2.setEnabled(false);
            this.FieldTlf3.setEnabled(false);

            //Se vuelve a mostrar la tabla actualizada: (Funcion no hecha aun)
            //this.tableLineas.setModel(lineas.mostrarDatosLineas());

            this.FieldRIF.setText("");
            this.FieldRS.setText("");
            this.FieldDirec.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "Por favor rellene los campos faltantes", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

        this.tableProveedores.setModel(prov.mostrarDatosProveedor());
    }//GEN-LAST:event_Guardar1ActionPerformed

    private void LimpiarTodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarTodo1ActionPerformed

        this.FieldRIF.setText("");
        this.FieldRS.setText("");
        this.FieldDirec.setText("");
        this.FieldMail1.setText("");
        this.FieldMail2.setText("");
        this.FieldMail3.setText("");
        this.FieldTlf1.setText("");
        this.FieldTlf2.setText("");
        this.FieldTlf3.setText("");
    }//GEN-LAST:event_LimpiarTodo1ActionPerformed

    private void Eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar1ActionPerformed
        int filaSeleccionada = this.tableProveedores.getSelectedRow();
        // prov.eliminarDatosProveedores(Integer.parseInt(this.FieldRIF.getText(filaSeleccionada,0)));
        int decision = JOptionPane.showConfirmDialog(null, "Seguro que desea elimimnar el Proveedor? ");
        if (decision == 0) {
            this.prov.eliminarDatosProveedores(Integer.parseInt(this.tableProveedores.getValueAt(filaSeleccionada, 0).toString()));
            this.tableProveedores.setModel(prov.mostrarDatosProveedor());
        }
    }//GEN-LAST:event_Eliminar1ActionPerformed

    private void VerInfo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerInfo1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Los datos del poveedor son\nRif: "+FieldRIF.getText()+"\n\n***Correo(s)*** "+
            prov.arreglocorreo(Integer.parseInt(this.FieldRIF.getText()))+"\n\n***Telefono(s)*** "+
            prov.arreglotlf(Integer.parseInt(this.FieldRIF.getText()))+"\n\n***Linea(s) a la(s) que suministran productos*** "+
            prov.arreglolineas(Integer.parseInt(this.FieldRIF.getText())));
    }//GEN-LAST:event_VerInfo1MouseClicked

    private void VerInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerInfo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerInfo1ActionPerformed

    private void FieldRIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldRIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldRIFActionPerformed

    private void MasMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasMailActionPerformed
        if (this.FieldMail2.isEnabled()==false && !(this.FieldMail1.getText().equals(""))){
            this.FieldMail2.setEnabled(true);
            FieldMail2.setVisible(true);
        }
        if (this.FieldMail3.isEnabled()==false && !(this.FieldMail2.getText().equals(""))){
            this.FieldMail3.setEnabled(true);
            FieldMail3.setVisible(true);
        }
    }//GEN-LAST:event_MasMailActionPerformed

    private void MasTlfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasTlfActionPerformed
        if (this.FieldTlf2.isEnabled()==false && !(this.FieldTlf1.getText().equals(""))){
            FieldTlf2.setVisible(true);
            this.FieldTlf2.setEnabled(true);
        }

        if (this.FieldTlf3.isEnabled()==false && !(this.FieldTlf2.getText().equals(""))){
            FieldTlf3.setVisible(true);
            this.FieldTlf3.setEnabled(true);
        }
    }//GEN-LAST:event_MasTlfActionPerformed

    private void FieldTlf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldTlf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldTlf2ActionPerformed

    private void LineaSuminist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineaSuminist1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LineaSuminist1ActionPerformed

    private void LineaSuminist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineaSuminist2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LineaSuminist2ActionPerformed

    private void LineaSuminist3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineaSuminist3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LineaSuminist3ActionPerformed

    private void tableProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProveedoresMouseClicked
        //Copiado de VUnidades.
        this.FieldRIF.setEnabled(false);
        this.FieldRS.setEnabled(true);
        this.FieldDirec.setEnabled(true);
        this.FieldMail1.setEnabled(true);
        this.FieldMail2.setEnabled(true);
        this.FieldMail3.setEnabled(true);
        this.FieldTlf1.setEnabled(true);
        this.FieldTlf2.setEnabled(true);
        this.FieldTlf3.setEnabled(true);
        this.FieldMail1.setEnabled(true);
        this.FieldMail2.setEnabled(true);
        this.FieldMail3.setEnabled(true);
        int filaSeleccionada = this.tableProveedores.rowAtPoint(evt.getPoint());
        this.FieldRIF.setText(this.tableProveedores.getValueAt(filaSeleccionada, 0).toString());
        this.FieldRS.setText(this.tableProveedores.getValueAt(filaSeleccionada, 1).toString());
        this.FieldDirec.setText(this.tableProveedores.getValueAt(filaSeleccionada, 2).toString());
        int[] data= new int[5];
        data= prov.datalineas(Integer.parseInt(this.FieldRIF.getText()));
        LineaSuminist1.setSelectedIndex(data[0]);
        LineaSuminist2.setSelectedIndex(data[1]);
        LineaSuminist3.setSelectedIndex(data[2]);
        String [] telefonos= new String [3];
        telefonos=prov.datatlf(Integer.parseInt(this.FieldRIF.getText()));
        FieldTlf1.setText(telefonos[0]);
        FieldTlf2.setText(telefonos[1]);
        FieldTlf3.setText(telefonos[2]);
        String [] correos = new String [3];
        correos=prov.dataemail(Integer.parseInt(this.FieldRIF.getText()));
        FieldMail1.setText(correos[0]);
        FieldMail2.setText(correos[1]);
        FieldMail3.setText(correos[2]);
    }//GEN-LAST:event_tableProveedoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar1;
    private javax.swing.JButton Eliminar1;
    private javax.swing.JTextField FieldDirec;
    private javax.swing.JTextField FieldMail1;
    private javax.swing.JTextField FieldMail2;
    private javax.swing.JTextField FieldMail3;
    private javax.swing.JTextField FieldRIF;
    private javax.swing.JTextField FieldRS;
    private javax.swing.JTextField FieldTlf1;
    private javax.swing.JTextField FieldTlf2;
    private javax.swing.JTextField FieldTlf3;
    private javax.swing.JButton Guardar1;
    private javax.swing.JButton LimpiarTodo1;
    private javax.swing.JComboBox<String> LineaSuminist1;
    private javax.swing.JComboBox<String> LineaSuminist2;
    private javax.swing.JComboBox<String> LineaSuminist3;
    private javax.swing.JButton MasMail;
    private javax.swing.JButton MasTlf;
    private javax.swing.JButton Nuevo1;
    private javax.swing.JButton VerInfo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableProveedores;
    // End of variables declaration//GEN-END:variables
}
